(function(global){
'use strict';
const Phase=Object.freeze({EMPTY:'empty',CONTAINMENT_DEFINED:'containment_defined',CONTAINMENT_VERIFIED:'containment_verified',PLASMA_ARMED:'plasma_armed',PLASMA_ACTIVE:'plasma_active',QUENCHED:'quenched',FAULT_LOCKED:'fault_locked'});
const PROFILES=Object.freeze({ACI:Object.freeze({name:'ACI',minBoundaryNodes:4,witnessSlots:3,approvalsRequired:2}),CUBIS:Object.freeze({name:'CUBIS',minBoundaryNodes:6,witnessSlots:3,approvalsRequired:2})});
class ContainmentError extends Error{constructor(message){super(message);this.name='ContainmentError';}}
function canonical(v){if(Array.isArray(v))return '['+v.map(canonical).join(',')+']';if(v&&typeof v==='object')return '{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}';return JSON.stringify(v);}
async function sha256Hex(v){const b=new TextEncoder().encode(typeof v==='string'?v:canonical(v));const d=await global.crypto.subtle.digest('SHA-256',b);return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('');}
class ContainmentGate{
 constructor(profile){this.profile=profile;this.phase=Phase.EMPTY;this.boundary=[];this.boundarySeal=null;this.witnesses=new Map();this.ledger=[];this.armedSeal=null;}
 static forSystem(system){const k=String(system||'').trim().toUpperCase();if(!PROFILES[k])throw new Error('unknown containment profile: '+system);return new ContainmentGate(PROFILES[k]);}
 async _sealBoundary(){return sha256Hex({profile:this.profile.name,boundary:this.boundary});}
 async _append(event,payload){const previousHash=this.ledger.length?this.ledger[this.ledger.length-1].eventHash:'0'.repeat(64);const body={seq:this.ledger.length,event,payload,previous_hash:previousHash};const eventHash=await sha256Hex(body);const row={seq:this.ledger.length,ts_ns:Date.now()*1000000,event,payload,previousHash,eventHash};this.ledger.push(row);return row;}
 async defineContainment(nodes){if(this.phase===Phase.PLASMA_ARMED||this.phase===Phase.PLASMA_ACTIVE)return this._fault('containment mutation attempted after plasma arm');const cleaned=[];for(const node of nodes||[]){const v=String(node).trim();if(v&&!cleaned.includes(v))cleaned.push(v);}if(cleaned.length<this.profile.minBoundaryNodes)throw new ContainmentError(`${this.profile.name} requires at least ${this.profile.minBoundaryNodes} boundary nodes`);this.boundary=cleaned;this.boundarySeal=await this._sealBoundary();this.witnesses.clear();this.armedSeal=null;this.phase=Phase.CONTAINMENT_DEFINED;await this._append('CONTAINMENT_DEFINED',{nodes:[...cleaned],seal:this.boundarySeal});return this.boundarySeal;}
 async witness(id,approve){if(this.phase!==Phase.CONTAINMENT_DEFINED&&this.phase!==Phase.CONTAINMENT_VERIFIED)throw new ContainmentError('witnessing is only valid before plasma arm');id=String(id||'').trim();if(!id)throw new Error('witnessId cannot be empty');if(!this.witnesses.has(id)&&this.witnesses.size>=this.profile.witnessSlots)throw new ContainmentError('witness slots are full');this.witnesses.set(id,!!approve);await this._append('WITNESS',{id,approve:!!approve});await this._recomputeVerification();}
 async _recomputeVerification(){if(this.boundarySeal!==await this._sealBoundary())return this._fault('boundary seal mismatch');const approvals=[...this.witnesses.values()].filter(Boolean).length;const full=this.witnesses.size===this.profile.witnessSlots;if(full&&approvals>=this.profile.approvalsRequired){if(this.phase!==Phase.CONTAINMENT_VERIFIED){this.phase=Phase.CONTAINMENT_VERIFIED;await this._append('CONTAINMENT_VERIFIED',{witnesses:this.witnesses.size,approvals,seal:this.boundarySeal});}}else if(this.phase===Phase.CONTAINMENT_VERIFIED){this.phase=Phase.CONTAINMENT_DEFINED;await this._append('CONTAINMENT_REVOKED',{witnesses:this.witnesses.size,approvals});}}
 async armPlasma(){if(this.phase!==Phase.CONTAINMENT_VERIFIED)throw new ContainmentError('plasma denied: containment is not verified');const current=await this._sealBoundary();if(!this.boundarySeal||current!==this.boundarySeal)return this._fault('plasma denied: containment seal mismatch');this.armedSeal=current;this.phase=Phase.PLASMA_ARMED;await this._append('PLASMA_ARMED',{seal:current});}
 async ignitePlasma(){if(this.phase!==Phase.PLASMA_ARMED)throw new ContainmentError('plasma denied: arm stage incomplete');if(this.armedSeal!==await this._sealBoundary())return this._fault('plasma denied: containment changed after arm');this.phase=Phase.PLASMA_ACTIVE;await this._append('PLASMA_ACTIVE',{seal:this.armedSeal});}
 async guard(){if(this.phase!==Phase.PLASMA_ARMED&&this.phase!==Phase.PLASMA_ACTIVE)return true;const current=await this._sealBoundary();const approvals=[...this.witnesses.values()].filter(Boolean).length;const quorumOk=this.witnesses.size===this.profile.witnessSlots&&approvals>=this.profile.approvalsRequired;const sealOk=current===this.boundarySeal&&current===this.armedSeal;if(!(quorumOk&&sealOk)){await this.quench('runtime containment guard failed');return false;}return true;}
 async quench(reason='manual'){const previous=this.phase;this.phase=Phase.QUENCHED;await this._append('QUENCH',{reason,from:previous});}
 async reset(){if(this.phase!==Phase.QUENCHED&&this.phase!==Phase.FAULT_LOCKED)throw new ContainmentError('reset is only allowed after quench/fault');this.boundary=[];this.boundarySeal=null;this.witnesses.clear();this.armedSeal=null;this.phase=Phase.EMPTY;await this._append('RESET',{});}
 async _fault(reason){const previous=this.phase;this.phase=Phase.FAULT_LOCKED;await this._append('FAULT_LOCKED',{reason,from:previous});throw new ContainmentError(reason);}
 async verifyLedger(){let previous='0'.repeat(64);for(let i=0;i<this.ledger.length;i++){const row=this.ledger[i];const body={seq:i,event:row.event,payload:row.payload,previous_hash:previous};const expected=await sha256Hex(body);if(row.seq!==i||row.previousHash!==previous||row.eventHash!==expected)return false;previous=row.eventHash;}return true;}
 async snapshot(){const approvals=[...this.witnesses.values()].filter(Boolean).length;return{system:this.profile.name,phase:this.phase,boundaryNodes:this.boundary.length,witnesses:this.witnesses.size,approvals,seal:this.boundarySeal,ledgerOk:await this.verifyLedger()};}
}
global.ACIContainment=Object.freeze({ContainmentGate,ContainmentError,Phase,PROFILES,sha256Hex});
})(typeof window!=='undefined'?window:globalThis);
